### ISSUE TITLE
Unable to click items in search uber bar

### ISSUE THREAD

**Issue by neoneddy** [modxcms/revolution#13404]
### Summary
In MODX 2.5.6, when I search for something I'm unable to click and goto the entry.

### Step to reproduce
Search for something in the uber bar

### Observed behavior

![image](https://cloud.githubusercontent.com/assets/819083/24477041/2b5f1504-149b-11e7-9973-1224e0c76af3.png)

### Expected behavior
That when I click, I can edit the resource or element

### Environment
MODX 2.5.6 , Apache, PHP7 , racksapce / liquidweb cloud sites

**Comment by Mark-H** [comment]
Confirmed in Chrome 56

```` 
Uncaught TypeError: e.stopPropagation is not a function
    at MODx.SearchBar.onSelect (modx.searchbar.js:334)
    at MODx.SearchBar.onViewClick (ext-all.js:21)
    at MODx.SearchBar.<anonymous> (modx.searchbar.js:302)
    at h.Event.fire (ext-all.js:21)
    at S.fireEvent (ext-all.js:21)
    at S.onClick (ext-all.js:21)
    at HTMLDivElement.I (ext-all.js:21)
````

I suspect it might be caused by the fixed keyboard usage in #13364... keyboard does work.

**Comment by pixelchutes** [comment]
Seems also pressing <kbd>Tab</kbd> from the uberbar search input triggers the same error as when clicking on a search result 😞 

> modx.jsgrps-min.js: Uncaught TypeError: e.stopPropagation is not a function

**Comment by pixelchutes** [comment]
@Mark-H @neoneddy I can confirm if I revert the change Mark suspected (#13364) that it indeed restores uberbar search result click functionality (Chrome 57).

**Comment by OptimusCrime** [comment]
If I get the time later today I'll try to fix this. We'd like to have this fixed before we upgrade sites for our customers. Is there a chance we can fix this issue and release a 2.6.7 hotfix?

**Comment by pixelchutes** [comment]
+1 for a hotfix (2.5.7 or 2.5.6-pl2 @opengeek?)

@OptimusCrime, we could quickly revert the offending commit 3672126, and spend more time on the Firefox issue (for the release after?) That's what I ended up doing locally, and I did have to run the `grunt` jobs to apply the fix to the minified JS.

**Comment by matdave** [comment]
Can confirm that @rtripault's solution fixes this issue. You can apply the file changes for a quick fix.

**Comment by pixelchutes** [comment]
While we wait for #13405 to be merged, I found you can right-click in the search results, then use "Open Link in New Tab" browser context menu option to bypass the JavaScript error as a workaround. This may be helpful to anyone unable to apply the patch manually who's already upgraded to 2.5.6.

**Comment by mindeffects** [comment]
I replaced "modx.searchbar.js" with this code (https://raw.githubusercontent.com/rtripault/revolution/3c7ecabffab1a72990fd2b658c4828346bf7fac9/manager/assets/modext/widgets/core/modx.searchbar.js).
In Chromium 55 I can now select a hit via the keyboard, but still not with the mouse.

**Comment by matdave** [comment]
Interesting! It solved my issue on Chrome 57 and Firefox 52 on Mac.

**Comment by rtripault** [comment]
You might need to disable js compression so it does not use the minified version (which does not have the changes)

**Comment by intersel** [comment]
Meet the same pb than mindeffects and with the js compression to off (compress_js) it's fixed... :-)
ouf!

**Comment by Jako** [comment]
2.5.7-dev contains now a compressed version: https://raw.githubusercontent.com/modxcms/revolution/ca5a9139e33cfa494fb03eb1cf71bd2e379b341a/manager/assets/modext/modx.jsgrps-min.js
