### ISSUE TITLE
Babel fails to create translation, strange 404 error

### ISSUE THREAD

**Issue by p-boiko** [modxcms/revolution#14192]
### Summary
Babel fails to create translation for resource.

### Step to reproduce
Open any resource or create a new one, click Create translation in any context you have.

### Observed behavior
"Please wait" alert shows up and hangs there forever.
In the console I see the following errors: JS requires assets/components/babel/conn/mgr.php through ajax request but fails with 404 server response.
But the script exists: https://i.imgur.com/nm9z1J7.png
It's readable (644) and all folders in it's tree are accessible (755)
In JS console I have the following error:
`TypeError: this.mask.addClass is not a function modx.jsgrps-min.js:1:113438`
`onShow https://my_domain/admin/assets/modext/modx.jsgrps-min.js:1`
`afterShow 3 ExtJS`
`onAjaxException https://my_domain/admin/assets/modext/core/modx.js?v=01cf0b4a:122`
`fire 3 ExtJS`
`f https://my_domain/admin/assets/ext3/adapter/ext/ext-base.js:21`
`m https://my_domain/admin/assets/ext3/adapter/ext/ext-base.js:21`
`createCallback https://my_domain/admin/assets/ext3/adapter/ext/ext-base.js:21`
Seems like this error is caused by the failed ajax request

### Expected behavior
A new resource should be created in a given context

### Environment
MODX Revolution 2.7.0-pl (advanced) (worked OK with prev. v2.6.5)
Babel: 3.0.0-pl
ExtJS: 3.4.1
Smarty: 3.1.27
10.2.19-MariaDB
PHP: 7.2
Lightspeed, modSecurity disabled
Firefox v65, Chromium v71, Gnome's Web v3.30.2

Happens after upgrade from v2.6.5 to v.2.7.0
Please somebody give me a hint what else should I check except modSecurity (off) and file permissions. I’m almost sure it’s rather a setup issue linked to the upgrade, not actually a bug in MODX code.
The same [issue](https://github.com/mikrobi/babel/issues/174#issue-389227835) in Babel's repository

**Comment by p-boiko** [comment]
No errors on a mirror site with the same setup. Sorry. Closed. Investigating.

**Comment by rthrash** [comment]
If you do find a bug, please open it at the Bable Github project. https://github.com/mikrobi/babel

**Comment by p-boiko** [comment]
> If you do find a bug, please open it at the Bable Github project. https://github.com/mikrobi/babel

Hi Ryan @rthrash
Sorry, but seams like it's rather a MODX bug, though hard to reproduce. When I rose log lovel to 4 I found this records:
`(WARN @ /some_path/core/cache/includes/elements/modplugin/15.include.cache.php : 146) PHP notice: Undefined index: xrouting-debug`
`(WARN @ /some_path/core/model/modx/modcontext.class.php : 248) `42` was requested but no alias was located.`
`(INFO in modContext::makeUrl @ resource 4) Resource with id 42 was not found in context web`
the resource 42 is indead missing. I deleted it some time ago for a reason I don’t remember. Now in process of creating a translation I have this error. Consequent number for resource to be created is 48. 

I can't reproduce this on my mirror site. I deleted, created resources and their translations in various consequences and the mirror just does what it should... I hope these log records will help somebody to help me...

**Comment by p-boiko** [comment]
the problem was in 0775 permissions instead of 0755 on `/assets` and `/assets/components` folders that caused error on my shared hosting

**Comment by danfox** [comment]
the permission of those folders are 755. 
Which other parameters should I check?

**Comment by JoshuaLuckers** [comment]
@danfox this issue is closed and will probably not be noticed by others. Feel free to create a new issue if you experience any issues.
