### PR TITLE
Implement isDirty function in MODx.panel.ImageTV

### LINKED ISSUE #15299: Button Close is not responding in resource manager window
### Summary
When try to close resource window in manager nothing happens.
Works on chunks etc. and when template is set as none.
Templates have few image TVs (MIGX resourceimages and single image file TVs)
Setting compress_js off not help.
Disabled form customization on template. No effect.
Browser console report:
```
Uncaught TypeError: b.isDirty is not a function
    ExtJS 3
        isDirty
        each
        isDirty
    isDirty https://www.xxxxx.fi/manager/assets/modext/modx.jsgrps-min.js:1
    cancel https://www.xxxxxx.fi/manager/assets/modext/sections/resource/update.js:90
    ExtJS 2
        onClick
        I
ext-all.js:21:600926
```
### Expected behavior
Should close resource window and go to start.

### Environment
MODX 2.8.0 (worked in 2.7.3)
PHP 7.2
apache
mysql
browser firefox and chrome

### PR DESCRIPTION
**Pull request by theboxer**
### What does it do?
Implements isDirty function in MODx.panel.ImageTV and for MODx.panel.FileTV

### Why is it needed?
Close button doesn't work on Resource, if you have image tv assigned to it.

### How to test
Add image TV to a template, edit resource using this template, hit close button. It will show an error in console about missing `isDirty` function.

### Related issue(s)/PR(s)
#15299

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
Can we have this for 2.x as well?

**Review by Ibochkarev — APPROVED** [review]
LGTM 👍

**Comment by JoshuaLuckers** [comment]
@theboxer can we get this for 2.x as well?

**Comment by Ibochkarev** [comment]
> @theboxer can we get this for 2.x as well?

https://github.com/modxcms/revolution/pull/15534

**Review by Ruslan-Aleev — APPROVED** [review]

**Review by alroniks — APPROVED** [review]
